# -----------------------------------------------------------------------------
# Site settings
# -----------------------------------------------------------------------------
name: Simone Hu
email: simone.hu@uwaterloo.ca
description: > # this means to ignore newlines until "url:"
footer_text: >
  Powered by coffee and bunnies. Based on the <a href="https://github.com/alshedivat/al-folio">al-folio</a> theme.

url: # the base hostname & protocol for your site
baseurl: # the subpath of your site, e.g. /blog/
last_updated: 01.06.2020 # leave blank if you don't want to display last updated

header: ['about', 'writing', 'teaching'] # header order and includes

# -----------------------------------------------------------------------------
# Open Graph
# -----------------------------------------------------------------------------
# Display links to the page with a preview object on social media.
# To achieve this, change serve_og_meta to true and then provide the URL of the
# preview image as the value of og_image.
serve_og_meta: false # Include Open Graph meta tags in the HTML head
og_image: # The site-wide (default for all links) Open Graph preview image

# -----------------------------------------------------------------------------
# Social integration
# -----------------------------------------------------------------------------
social_header: true # have social icons in header
github_username: simonehu # your GitHub user name
twitter_username: # your Twitter handle
linkedin_username: # your LinkedIn user name
scholar_userid: # your Google Scholar ID
orcid_id: # your ORCID ID
medium_username: # your Medium username
quora_username: # your Quora username
publons_id: # your ID on Publons
research_gate_profile: # your profile on ResearchGate
blogger_url: # your blogger URL

contact_note: >

google_analytics: # your google-analytics code

# -----------------------------------------------------------------------------
# Blog
# -----------------------------------------------------------------------------
blog_name: thoughts.
blog_description:

# Pagination
paginate: 4
permalink: /blog/:year/:month/:title/
paginate_path: /blog/page:num/

text:
  pagination:
    newer: 'Newer'
    older: 'Older'

# Comments
disqus_shortname: # put your disqus shortname

# Optional features
show_social_icons:  false
enable_anchorjs:    false
enable_katex:       true

# -----------------------------------------------------------------------------
# Collections
# -----------------------------------------------------------------------------
collections:
  news:
    defaults:
      layout: post
    output: true
    permalink: /news/:title/
  projects:
    output: true
    permalink: /projects/:title/
  travels:
    output: true
    permalink: /travels/:title/

news_limit: 5
news_term: W2020

# -----------------------------------------------------------------------------
# Jekyll settings
# -----------------------------------------------------------------------------

# Build settings
markdown: kramdown
kramdown:
  math_engine: mathjax
highlighter: pygments

# Includes & excludes
include: ['_pages']
exclude: [vendor]

# Plug-ins
plugins:
    - jekyll-email-protect
    - jekyll-paginate
    - jekyll/scholar
    - jemoji

# Jekyll-Scholar
scholar:

  last_name: Hu

  style: apa
  locale: en

  sort_by: year,month
  order: descending
  group_by: type
  type_names: { article: publications and preprints, conference: posters }

  source: /_bibliography/
  bibliography: publications.bib
  bibliography_template: bib
  bibtex_filters:

  replace_strings: true
  join_strings: true

  details_dir: bibliography
  details_layout: bibtex.html
  details_link: Details

  query: "@*"

# -----------------------------------------------------------------------------
# Other settings
# -----------------------------------------------------------------------------
jquery_version: "3.4.1"
katex_version: "0.11.1"
anchorjs_version: "4.2.2"
